# ===============================
# Configuration for Parquet -> MinIO (Destination)
# ===============================

[parquet_to_minio.destination.filesystem]
bucket_url = "s3://taxis"

[parquet_to_minio.destination.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password"
endpoint_url = "http://minio:9000"

# ===============================
# Configuration for MinIO -> ADLS (Source)
# ===============================

[s3_to_adls.sources.filesystem]
bucket_url = "s3://taxis/taxis_parquet/df_data"

[s3_to_adls.sources.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password"
endpoint_url = "http://minio:9000"

# ===============================
# Configuration for MinIO -> ADLS (Destination)
# ===============================

[s3_to_adls.destination.filesystem]
bucket_url = "abfss://<YOUR_CONTAINER_NAME>@<YOUR_ACCOUNT_NAME>.dfs.core.windows.net/<YOUR_FOLDER>"


[s3_to_adls.destination.filesystem.credentials]
azure_storage_account_name = "<YOUR_AZURE_ACCOUNT_NAME>"
azure_storage_account_key = "<YOUR_AZURE_ACCOUNT_KEY>"


# ===============================
# ClickHouse Credentials Configuration
# ===============================

[destination.clickhouse.credentials]
database = "default"
username = "default"
password = "default"
host = "clickhouse"         # if the pipeline runs within the same Docker network
port = 9000                 # internal container port (native TCP)
http_port = 8123            # exposed HTTP port
secure = 0                  # no TLS

# ===============================
# General ClickHouse Configuration
# ===============================
[destination.clickhouse]
dataset_table_separator = "___"                         # Default separator for table names derived from the dataset
table_engine_type = "merge_tree"                        # Default table engine type
dataset_sentinel_table_name = "dlt_sentinel_table"      # Default sentinel table name
staging_use_https = true                                # Whether to connect to the staging bucket via HTTPS (default is True)